from django.urls import path
from . import  views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # URLs do cliente:
    path('cliente/', views.cliente, name='cliente'), 
    path('tickets_gerente/', views.tickets_gerente, name='tickets_gerente'),
    path('pedido_cliente_gerente/', views.pedido_cliente_gerente, name='pedido_cliente_gerente'),
    path('adicionar_ao_carrinho/<int:produto_id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('perfil_cliente/', views.perfil_cliente, name='perfil_cliente'),
    path('carrinho/', views.carrinho, name='carrinho'),
    path('finalizar_compra/', views.finalizar_compra, name='finalizar_compra'),
    path('remover/<int:produto_id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('historico_cliente/', views.historico_cliente, name='historico_cliente'), 
    path('login_cliente/', views.login_cliente, name='login_cliente'),
    path('valida_login_cliente/', views.valida_login_cliente, name='valida_login_cliente'),
    path('cadastro_cliente/', views.cadastro_cliente, name='cadastro_cliente'),
    path('valida_cadastro_cliente/', views.valida_cadastro_cliente, name='valida_cadastro_cliente'),
    path('listar_faturas/', views.listar_faturas, name='listar_faturas'),
    path('fatura/<int:fatura_id>/', views.ver_fatura, name='ver_fatura'),
    path('produto/<int:produto_id>/', views.produto_detalhe, name='produto_detalhe'),
    path('produtos/<int:produto_id>/', views.produtos_detalhe, name='produtos_detalhe'),
    path('produto_cliente/', views.produto_cliente, name='produto_cliente'),
    path('ver_produto_empresa/', views.ver_produto_empresa, name='ver_produto_empresa'),
    path('contacto_cliente/', views.contacto_cliente, name='contacto_cliente'),
    path('pesquisare/', views.pesquisare, name='pesquisare' ),
    path('editar_perfil/<int:pk>/', views.editar_perfil, name='editar_perfil'),
    path('suporte/', views.suporte, name='suporte'),
    path('enviar-ticket/', views.enviar_suporte, name='enviar_ticket'),
    path('avaliar_produto/', views.avaliar_produto, name = "avaliar_produto"),


    
    # URLs do Gerente:
    path('gerente/', views.gerente, name='gerente'),
    path('perfil_gerente/', views.perfil_gerente, name='perfil_gerente'),
    path('contactar_cliente/', views.contactar_cliente, name='contactar_cliente'),
    path('listar_cliente/', views.listar_cliente, name='listar_cliente'),
    path('historico_gerente/', views.historico_gerente, name='historico_gerente'),
    path('login_gerente/', views.login_gerente, name='login_gerente'),
    path('valida_login_gerente/', views.valida_login_gerente, name='valida_login_gerente'),
    path('conta_login_gerente/', views.conta_login_gerente, name='conta_login_gerente'),
    path('valida_cadastro_gerente_cliente/', views.valida_cadastro_gerente_cliente, name='valida_cadastro_gerente_cliente'),
    path('nossos_clientes/', views.nossos_clientes, name='nossos_clientes'),
    path('adicionar_produto/', views.adicionar_produto, name='adicionar_produto'),
    path('adicionar_cliente/', views.adicionar_cliente, name='adicionar_cliente'),
    path('adicionar_empresa/', views.adicionar_empresa, name='adicionar_empresa'),
    path('excluir_usuario/<int:id>/', views.excluir_usuario, name='excluir_usuario'),
    path('eliminar_fornecedor/<int:id>/', views.eliminar_fornecedor, name='eliminar_fornecedor'),
    path('marca/', views.marca, name='marca'),
    path('categoria/', views.categoria, name='categoria'),
    path('fornecedor/', views.fornecedor, name='fornecedor'),
    path('adicionar_categoria/', views.adicionar_categoria, name='adicionar_categoria'),
    path('minha_categoria/', views.minha_categoria, name='minha_categoria'),
    path('criar_fornecedor/', views.criar_fornecedor, name='criar_fornecedor'),
    path('detalhes_produto/', views.detalhes_produto, name='detalhes_produto'),

    # URLs das Empresas:
    path('empresa/', views.empresa, name='empresa'),
    path('contato/', views.contato_view, name='contato_view'),
    path('pedido_empresa_gerente/', views.pedido_empresa_gerente, name='pedido_empresa_gerente'),
    path('listar_faturas_empresas/', views.listar_faturas_empresas, name= 'listar_faturas_empresas'),
    path('contacto_empresa/', views.contacto_empresa, name='contacto_empresa'),
    path('perfil_empresa/', views.perfil_empresa, name='perfil_empresa'),
    path('carrinho_empresa/', views.carrinho_empresa, name='carrinho_empresa'),
    path('pagamentos/<int:pedido_id>/', views.pagamentos_empresa, name='pagamentos_empresa'),
    path('finalizar_compra_empresa/', views.finalizar_compra_empresa, name='finalizar_compra_empresa'),
    path('adicionar_ao_carrinho_empresa/<int:produto_id>/', views.adicionar_ao_carrinho_empresa, name='adicionar_ao_carrinho_empresa'),
    path('login_empresa/', views.login_empresa, name='login_empresa'),
    path('historico_empresa/', views.historico_empresa, name='historico_empresa'),
    path('valida_login_empresa/', views.valida_login_empresa, name='valida_login_empresa'),
    path('cadastro_empresa/', views.cadastro_empresa, name='cadastro_empresa'),
    path('valida_cadastro_empresa/', views.valida_cadastro_empresa, name='valida_cadastro_empresa'),

    # URLs relacionadas à compra: 
    path('pagamento/<int:pedido_id>/', views.pagamento_view, name='pagamento'),
    path('sucesso/<int:fatura_id>/', views.sucesso, name='sucesso'),
    path('faturas/', views.listar_faturas, name='listar_faturas'),
    path('fatura/<int:id>/', views.visualizar_fatura, name='visualizar_fatura'),
    path('fatura/<int:pedido_id>/', views.gerar_fatura, name='gerar_fatura'),
    path('estoque/', views.lista_estoque, name='lista_estoque'),
    path('faturas/', views.lista_faturas, name='lista_faturas'),
    path('estoque/eliminar/<int:id>/', views.eliminar_estoque, name='eliminar_estoque'), 
    path('pesquisar/', views.pesquisar, name='pesquisar'),
    path('pesquisar_ver/', views.pesquisar_ver, name='pesquisar_ver'),
    path('pesquisar_cliente/', views.pesquisar_cliente, name='pesquisar_cliente'),
    path('motor/', views.motor, name='motor'),
    path('detalhe_produto/<int:produto_id>/', views.detalhe_produto, name='detalhe_produto'),
    path('freio/', views.freio, name='freio'),
    path('eletrico/', views.eletrico, name='eletrico'),
    path('carroceria/', views.carroceria, name='carroceria'),
    path('transmissao/', views.transmissao, name='transmissao'),
    path('suspensao/', views.suspensao, name='suspensao'),
    path('faturas/eliminar/<int:fatura_id>/', views.eliminar_fatura, name='eliminar_fatura'),
    path('interior_conforto/', views.interior_conforto, name='interior_conforto'),
    path('noticia/', views.noticia, name='noticia'),
    path('sair/', views.sair, name='sair'),
    path('eliminar_cliente/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('clientes_cadastrados/',views.clientes_cadastrados, name='clientes_cadastrados' ),
    path('visao_geral/', views.visao_geral, name='visao_geral'),
    path('ticket/<int:id>/', views.ticket_detalhes, name='ticket_detalhes'),
    path('ticket/<int:id>/atualizar/', views.atualizar_ticket, name='atualizar_ticket'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
