# Generated by Django 5.1 on 2024-08-27 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categoria do produto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Conta dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Condição do produto',
            },
        ),
        migrations.CreateModel(
            name='contactar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('assunto', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contactos/Dividas',
            },
        ),
        migrations.CreateModel(
            name='Contato_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Conta dos Empresas',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='imagem/')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Conta do gerente',
            },
        ),
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='imagem/')),
            ],
            options={
                'verbose_name_plural': 'Marcas na pagina principal',
            },
        ),
        migrations.CreateModel(
            name='Marca_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marcas dos produtos',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagem/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Video Principal',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos_empresa', to='usuarios.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gerente')),
            ],
            options={
                'verbose_name_plural': 'chat online',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Nossas_faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('endereco_entrega', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='faturas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='imagem/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=600)),
                ('estoque', models.CharField(max_length=40)),
                ('preco', models.FloatField()),
                ('preco_promocional', models.FloatField()),
                ('imagem', models.FileField(upload_to='imagem/')),
                ('peso', models.FloatField()),
                ('dimensao', models.CharField(max_length=50)),
                ('compatibilidade', models.CharField(max_length=50)),
                ('quantidade_fornecida', models.IntegerField()),
                ('material', models.CharField(max_length=50)),
                ('instrucao_instalacao', models.TextField(blank=True, max_length=300)),
                ('garantia', models.CharField(max_length=50)),
                ('prazo_entrega', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_produto')),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.condicao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.fornecedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.marca_produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.produtos'),
        ),
        migrations.CreateModel(
            name='ItemPedidoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='usuarios.pedido_empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido_set', to='usuarios.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='usuarios.carrinho')),
                ('carrinho_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho_empresa', to='usuarios.carrinho_empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='usuarios.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho_empresa',
            name='produtos',
            field=models.ManyToManyField(related_name='carrinhos_empresa', through='usuarios.ItemCarrinho', to='usuarios.produtos'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(related_name='carrinhos_cliente', through='usuarios.ItemCarrinho', to='usuarios.produtos'),
        ),
    ]
