# Generated by Django 5.1 on 2024-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome_produto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
