# Generated by Django 5.1 on 2024-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_pedido_nome_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagem/'),
        ),
    ]
