# Generated by Django 5.1 on 2024-08-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoria_produto_cliente_condicao_contactar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='numero_fatura',
        ),
    ]
