# Generated by Django 5.1 on 2024-08-12 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_fatura_numero_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='usuarios.cliente')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
