# Generated by Django 5.0.4 on 2024-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='imagem',
            field=models.FileField(default=1, upload_to='imagem/'),
            preserve_default=False,
        ),
    ]
