# Generated by Django 5.1 on 2024-08-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
    ]
