# Generated by Django 5.1 on 2024-08-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_carrinho_endereco_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='foto',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
