# Generated by Django 5.1 on 2024-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_cliente_email_alter_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='nif',
            field=models.CharField(max_length=60),
        ),
    ]
