# Generated by Django 5.0.4 on 2024-07-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido_set', to='usuarios.pedido'),
        ),
    ]
