# Generated by Django 5.0.4 on 2024-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
