# Generated by Django 5.0.4 on 2024-07-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
    ]
