# Generated by Django 5.0.4 on 2024-07-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_remove_carrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='imagem',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.produtos'),
            preserve_default=False,
        ),
    ]
