# Generated by Django 5.0.4 on 2024-07-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto', 'cliente')},
        ),
    ]
