# Generated by Django 5.0.4 on 2024-07-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_remove_carrinho_cliente_remove_carrinho_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='usuarios.cliente'),
            preserve_default=False,
        ),
    ]
