# Generated by Django 5.0.4 on 2024-07-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_carrinho_cliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(related_name='carrinhos', through='usuarios.ItemCarrinho', to='usuarios.produtos'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='usuarios.cliente'),
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='cliente',
        ),
    ]
