# Generated by Django 5.0.4 on 2024-07-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_fatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={},
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
