# Generated by Django 5.0.4 on 2024-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_alter_fatura_options_alter_fatura_data_emissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido'),
        ),
    ]
