# Generated by Django 5.0.4 on 2024-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='url',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='imagem/'),
        ),
    ]
