# Generated by Django 5.0.4 on 2024-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_remove_noticia_url_alter_noticia_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='imagem/')),
            ],
            options={
                'verbose_name_plural': 'Marcas na pagina principal',
            },
        ),
    ]
