# Generated by Django 5.0.4 on 2024-07-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_alter_pedido_status_alter_video_video_pedido_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(related_name='carrinhos_cliente', through='usuarios.ItemCarrinho', to='usuarios.produtos'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='usuarios.carrinho'),
        ),
        migrations.CreateModel(
            name='Carrinho_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_empresa', to='usuarios.empresas')),
                ('produtos', models.ManyToManyField(related_name='carrinhos_empresa', through='usuarios.ItemCarrinho', to='usuarios.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho_empresa', to='usuarios.carrinho_empresa'),
        ),
    ]
