# Generated by Django 5.0.4 on 2024-07-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_alter_carrinho_produtos_alter_itemcarrinho_carrinho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='cliente',
        ),
        migrations.AddField(
            model_name='fatura',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas'),
            preserve_default=False,
        ),
    ]
