# Generated by Django 5.0.4 on 2024-07-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_remove_fatura_cliente_fatura_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas'),
        ),
    ]
