# Generated by Django 5.0.4 on 2024-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_contato_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.FileField(default=1, upload_to='imagem/'),
            preserve_default=False,
        ),
    ]
