# Generated by Django 3.2.16 on 2024-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_pedido_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibam', models.CharField(max_length=100)),
            ],
        ),
    ]
