# Generated by Django 3.2.16 on 2024-08-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_empresa',
            name='imagem',
            field=models.FileField(default=1, upload_to='imagem/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemPedidoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido_empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produtos')),
            ],
        ),
    ]
