# Generated by Django 3.2.16 on 2024-08-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos_cliente', to='usuarios.empresas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho_empresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos_empresa', to='usuarios.empresas'),
        ),
    ]
