# Generated by Django 3.2.16 on 2024-08-09 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
